# Generated by Django 6.0.1 on 2026-01-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offline_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.CharField(max_length=3)),
                ('food_name', models.CharField(max_length=50)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('food_image', models.ImageField(upload_to='Offline_menu/')),
                ('food_descriprion', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_special', models.BooleanField(default=False)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='menu.food_category')),
            ],
        ),
        migrations.CreateModel(
            name='Online_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_image', models.ImageField(upload_to='menu/online_menu')),
                ('food_name', models.CharField(max_length=50)),
                ('food_details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.FloatField()),
                ('is_special', models.BooleanField(default=False)),
                ('is_offer', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.food_category')),
            ],
        ),
    ]
